name: Attach avatars to release assets

on:
  release:
    types:
      - released
      - prereleased

jobs:
  get_avatar_branches:
    name: Get avatar branches
    uses: ./.github/workflows/get_target_branches.yml
    with:
      include_base: false
  attach_avatar:
    name: Attach avatars to release assets
    needs: get_avatar_branches
    permissions:
      contents: write
    uses: Gakuto1112/MyFiguraAvatarPacker/.github/workflows/attach_avatars.yml@main
    with:
      target_branches: ${{ needs.get_avatar_branches.outputs.target_branches }}
      should_show_branch_name: true
      update_checker_script_included: true
      path_to_update_checker: './scripts/avatar_modules/action_wheel/update_checker.lua'
      should_replace_branch_name: true