name: Change dev version

on:
  workflow_dispatch:
    inputs:
      versionMajor:
        description: Major value
        required: true
        type: number
        default: 1
      versionMinor:
        description: Minor value
        required: true
        type: number
        default: 0
      versionPatch:
        description: Patch value
        required: true
        type: number
        default: 0

jobs:
  check_inputs:
    name: Check inputs
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          if ! echo ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH} | grep -E "^([0-9]+\.){2}[0-9]+$" > /dev/null; then
              echo "::error::Version numbers must be nonnegative integers."
              exit 1
          fi
        env:
          VERSION_MAJOR: ${{ inputs.versionMajor }}
          VERSION_MINOR: ${{ inputs.versionMinor }}
          VERSION_PATCH: ${{ inputs.versionPatch }}
  get_avatar_branches:
    name: Get avatar branches
    needs: check_inputs
    uses: ./.github/workflows/get_target_branches.yml
    with:
      include_base: true
  change_dev_version:
    name: Change dev version
    needs: get_avatar_branches
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target_branch: ${{ fromJSON(needs.get_avatar_branches.outputs.target_branches) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ matrix.target_branch }}
      - name: Change development version on the script
        run: sed -i -e "s/instance\.AVATAR_VERSION\s=\s\".*\"/instance.AVATAR_VERSION = \"${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}_dev\"/g" ./scripts/avatar_modules/action_wheel/update_checker.lua
        env:
          VERSION_MAJOR: ${{ inputs.versionMajor }}
          VERSION_MINOR: ${{ inputs.versionMinor }}
          VERSION_PATCH: ${{ inputs.versionPatch }}
      - id: check_diff
        name: Check diff
        continue-on-error: true
        run: |
          git add -N --all
          git diff --exit-code
      - id: configure_git
        name: Configure Git user
        if: ${{ steps.check_diff.outcome == 'failure' }}
        run: |
          git remote set-url origin https://github-actions:${TOKEN}@github.com/${REPOSITORY}
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
      - name: Commit and push
        if: ${{ steps.configure_git.conclusion == 'success' }}
        run: |
          git add --all
          git commit -m '[GitHub Actions] 開発バージョンを変更'
          git push origin
